version: '3'

services:

  nodeos:
    container_name: nodeos
    image: eostestnet
    command: nodeos -e -p eosio --genesis-json /root/.local/share/eosio/nodeos/config/genesis.json --plugin eosio::producer_plugin --plugin eosio::http_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console --http-validate-host=false --filter-on="*"
    stop_grace_period: 3m0s
    volumes:
      - ./contracts/:/root/contracts
      - ./config.ini:/root/.local/share/eosio/nodeos/config/config.ini
      - ./genesis.json:/root/.local/share/eosio/nodeos/config/genesis.json
    ports:
      - '8888:8888'
      - '9830:9876'
    depends_on:
      - keosd

  keosd:
    container_name: keosd
    hostname: keosd
    image: eostestnet
    command: keosd --http-server-address=0.0.0.0:8901 --http-validate-host 0 --verbose-http-errors --unlock-timeout=9999999
    volumes:
      - ./default.wallet:/root/eosio-wallet/default.wallet
    expose:
      - 8901
    ports:
      - '8901:8901'
