version: '3'

services:

  steem:
    container_name: steem
    hostname: steem
    image: steemit/steem:latest
    command: /usr/local/steemd-testnet/bin/steemd --data-dir /steemd-data
    volumes:
      - ../networks/steem/data/:/steemd-data
    ports:
      - '8090:8090'
    restart: always
    networks:
      - testnet

  steem-wallet:
    container_name: steem-wallet
    hostname: steem-wallet
    image: steemit/steem:latest
    command: /usr/local/steemd-testnet/bin/cli_wallet -w /steemd-data/wallet.json -d -s ws://steem:8090 -H 0.0.0.0:8091 --rpc-http-allowip 172.17.0.1 --rpc-http-allowip 172.18.0.1 --rpc-http-allowip 172.28.0.1
    volumes:
      - ../networks/steem/data/:/steemd-data
    ports:
      - '8091:8091'
    restart: always
    networks:
      - testnet

networks:
  testnet:
