version: '3'

services:

  nodeos:
    container_name: nodeos
    hostname: nodeos
    build:
      context: .
      dockerfile: build-eosio-testnet.dockerfile
    image: eosio-testnet:latest
    command: nodeos --config-dir /root/.local/share/eosio/nodeos/config/ --config config.ini --logconf /root/.local/share/eosio/nodeos/config/logging.json --genesis-json /root/.local/share/eosio/nodeos/config/genesis.json
    stop_grace_period: 1m0s
    networks:
      - eosiobridge
    volumes:
      - ../eosio/contracts/:/root/contracts
      - ../eosio/data/logging.json:/root/.local/share/eosio/nodeos/config/logging.json
      - ../eosio/data/genesis.json:/root/.local/share/eosio/nodeos/config/genesis.json
      - ../eosio/data/config.ini:/root/.local/share/eosio/nodeos/config/config.ini
    ports:
      - '8888:8888'
    depends_on:
      - keosd

  keosd:
    container_name: keosd
    hostname: keosd
    build:
      context: .
      dockerfile: build-eosio-testnet.dockerfile
    image: eosio-testnet:latest
    command: keosd --http-server-address=0.0.0.0:8901 --http-validate-host 0 --verbose-http-errors --unlock-timeout=9999999
    networks:
      - eosiobridge
    volumes:
      - ../eosio/data/default.wallet:/root/eosio-wallet/default.wallet
    expose:
      - 8901
    ports:
      - '8901:8901'

  pricefeed:
    container_name: pricefeed
    hostname: pricefeed
    build:
      context: .
      dockerfile: delphioracle.dockerfile
    image: delphioracle:latest
    command: /bin/sh /delphioracle/scripts/update-docker.sh
    networks:
      - eosiobridge
    depends_on:
      - nodeos

  writehash:
    container_name: writehash
    hostname: writehash
    build:
      context: .
      dockerfile: delphioracle.dockerfile
    image: delphioracle:latest
    command: /bin/sh /delphioracle-rng-script/run.sh
    networks:
      - eosiobridge
    depends_on:
      - nodeos

networks:
  eosiobridge:
